//@version=5
strategy("Auto_breakout_3514", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// Input Parameters
int bbLength = 20 // Bollinger Bands Length
float bbMult = 2.0 // Bollinger Bands Standard Deviation Multiplier

// Indicators
[middle, upper, lower] = ta.bb(close, 20, 2.0)

// Strategy Logic
longCondition = close > upper and close[1] <= upper[1]
shortCondition = close < lower and close[1] >= lower[1]

// Entry conditions
if (longCondition)
    strategy.entry("Long", strategy.long)

if (shortCondition)
    strategy.entry("Short", strategy.short)

// Exit conditions
longExitCondition = close < middle
shortExitCondition = close > middle

if (longExitCondition)
    strategy.close("Long")

if (shortExitCondition)
    strategy.close("Short")

// Optional: Risk Management

strategy.exit("TP", "Long", limit=strategy.position_avg_price * (1 + 6.810570673100475 / 100))
strategy.exit("TP", "Short", limit=strategy.position_avg_price * (1 - 6.810570673100475 / 100))

// Plotting
plot(middle, color=color.yellow, title='BB Middle')
plot(upper, color=color.red, title='BB Upper')
plot(lower, color=color.green, title='BB Lower')
 